### ISSUE TITLE
Script Encoded / Obfuscated

### ISSUE THREAD

**Issue by 3lpsy** [Sikkandar-Sha/SEC-AUDIT#1]
Hi,

This is a fantastic script. I've run it in a VM and want to run it on production. However, I can't run it unless I can review the deobfuscated code.

Is there a chance you can point me to deobfuscated version? Is there a reason you encoded the script in such a way?

Thanks!

**Comment by Sikkandar-Sha** [comment]
The script is encoded intentionally. Contact me on email.

**Comment by rjsandoval** [comment]
Can I get a copy of this too?

**Comment by Sikkandar-Sha** [comment]
The reason I encoded the script is because so many people started using the
script by renaming the author field to their own name.
The script came back to me eventually with some one stating that that is
their proprietary script.

Regards,
Sikkandar Sha

**Comment by Sikkandar-Sha** [comment]
The reason I encoded the script is because so many people started using the
script by renaming the author field to their own name.
The script came back to me eventually with some one stating that that is
their proprietary script.

Regards,
Sikkandar Sha

**Comment by Sikkandar-Sha** [comment]
The reason I encoded the script is because so many people started using the script by renaming the author field to their own name. The script came back to me eventually with some one stating that it is their proprietary script.

However I have added a clue in the code itself with which one could get the decoded version of the same. Try it. Good Luck! If you are unable to then let me know.
